### ISSUE TITLE
Doc diff as a library

### ISSUE THREAD

**Issue by de-code** [ckorzen/arxiv-benchmark#1]
Hi,

I was wondering whether you'd consider making the doc diff part a library?
I used initially for an evaluation as well - although I ended up just using word differences.
As part of that I also created something that generated an HTML diff (similar to the coloured diff you generate for the console) - that could be fed back if you are interested.

Also, what license is that code in please?

Thank you

**Comment by ckorzen** [comment]
Yes, it is definitely planned to move the doc diff part into a library. But I'm not sure if I can make it in the near future. 
The license of the code will be defined soon.

**Comment by de-code** [comment]
Hi Claudius, I was wondering whether you have any update on the license?

(We like to release our code under MIT, so a compatible license would be great)

**Comment by ckorzen** [comment]
Hi Daniel, thanks for the reminder. The code is now licensed under the MIT license.

**Comment by de-code** [comment]
That's perfect, thank you.
